### ISSUE TITLE
Deprecate the remix-edge-template in favour of Netlify Edge Functions support directly in Remix

### ISSUE THREAD

**Issue by nickytonline** [netlify/remix-edge-template#19]
## Description

Deprecate the remix-edge-template in favour of Netlify Edge Functions support directly in Remix.

## Related Issues, PRs and Documents

https://github.com/remix-run/remix/pull/3104

**Comment by ascorbic** [comment]
Deprecate but not delete, because it's in several examples.

**Comment by nickytonline** [comment]
Just waiting to hear back from the Remix team about how we're handling this, i.e. not modifying the Remix compiler code. See https://github.com/remix-run/remix/pull/3104#issuecomment-1119786482 and https://discord.com/channels/770287896669978684/928816717172445204/972164970617917520

**Comment by nickytonline** [comment]
We're no longer deprecating this. This will still be the repo for the Netlify Edge Remix template.
