### ISSUE TITLE
Brand new install: 

### ISSUE THREAD

**Issue by msevestre** [netlify/remix-edge-template#35]
I just followed the steps in the read me.
`npx create-remix@latest --template netlify/remix-edge-template`

This is what I am getting by starting this template

![image](https://user-images.githubusercontent.com/1041237/174919382-416014dc-8bc0-4b3c-9e61-b4374105d064.png)

Is there another step that needs to be performed?

**Comment by segheysens** [comment]
I am seeing this error as well, did you find a solution @msevestre?

**Comment by msevestre** [comment]
@segheysens nope.
I moved to fly.io. I would love to use netlify because I used them for many other react project. I just don't think this stack is ready quite yet.

**Comment by segheysens** [comment]
I updated remix to allow for ^0.11 of @netlify/functions like mentioned here: https://github.com/remix-run/remix/pull/2313/files

I think that was the issue!

**Comment by msevestre** [comment]
Cool. I am going to try this out then;-)

**Comment by nickytonline** [comment]
I'm going to go ahead and close this as the official template will be coming soon. It's based off of work in https://github.com/netlify/remix-compute/pull/16.
