### ISSUE TITLE
Issue with React Types? - Duplicate identifier 'LibraryManagedAttributes' 

### ISSUE THREAD

**Issue by DroopyTersen** [netlify/remix-edge-template#5]
## Replication Steps
1. Clone the repo
3. `npm install`
4. `npm install @remix-run/netlify-edge` 
   - not sure if this is necessary but it seemed like it was missing
   - I tried it with and without this
5. `npm run dev`

Where are the React 18 types are coming from? I didn't change `package.json` which is setup for React 17. Grasping at straws I tried upgrading to React 18 but still had the issue.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/4020046/164098927-33d5a8a9-e113-4a6d-89d8-bcf2942d3c5e.png">

```
error: TS2300 [ERROR]: Duplicate identifier 'LibraryManagedAttributes'.
        type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
             ~~~~~~~~~~~~~~~~~~~~~~~~
    at https://cdn.esm.sh/v77/@types/react@18.0.1/index.d.ts:3103:14

    'LibraryManagedAttributes' was also declared here.
            type LibraryManagedAttributes<C, P> = C extends React.MemoExoticComponent<infer T> | React.LazyExoticComponent<infer T>
                 ~~~~~~~~~~~~~~~~~~~~~~~~
        at https://cdn.esm.sh/v77/@types/react@18.0.5/index.d.ts:3123:14
```

**Comment by nickytonline** [comment]
There is a PR up for upgrading to React 18, see #4, however, this is not where the duplicate types issue lies. It's on the Deno side of things from what I can tell.

There are two different versions of the types are being referenced via the URL imports in, https://github.com/remix-run/remix/blob/experimental-netlify-edge/packages/remix-netlify-edge/mod.ts (import via https://esm.sh/@remix-run/server-runtime@1.4.1), and here https://github.com/remix-run/remix/blob/experimental-netlify-edge/packages/remix-netlify-edge/server.ts (import via https://esm.sh/@remix-run/server-runtime@1.3.5?pin=v77).

I'll let @ascorbic chime in here as well as I know he did a bit of digging as well.

**Comment by ascorbic** [comment]
This is a PR to fix it in the Deno adapter: https://github.com/remix-run/remix/pull/2931

**Comment by nickytonline** [comment]
This should no longer be an issue since https://github.com/remix-run/remix/pull/2931 was merged. I'm going to go ahead and close this issue.

**Comment by nickytonline** [comment]
Note that this was a bug, but not with the Remix Edge template.
