### ISSUE TITLE
Remix Example 

### ISSUE THREAD

**Issue by Bojne** [netlify/remix-edge-template#8]
Hi! This project looks cool. I wonder if there's a deployed version of the project on Netlify, and if you can you add in the link to the repo?

🙏🏻 , 
Yueh-Han

**Comment by nickytonline** [comment]
Hi @Bojne! I'm glad you thing the project looks cool! 😎

 If you want to try it out, there is a Deploy to Netlify button in this [repository's README fille](https://github.com/netlify/remix-edge-template#readme).

![CleanShot 2022-04-20 at 14 10 29](https://user-images.githubusercontent.com/833231/164295449-4d4eef23-20a3-4302-b168-60a731ed70cb.png)
